language: bash

sudo: required

services: 
  - docker

# before_install:
#   - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
#   - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker build -t rtxverma123/flaskblog .
#   - docker push rtxverma123/flaskblog
  
install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config

scripts: 
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker build -t rtxverma123/flaskblog .
   - docker push rtxverma123/flaskblog
   - kubectl apply -f deploy.yml
   - kubectl apply -f service.yml
